org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx2G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false
org.gradle.logging.level=quiet
android.enableR8.fullMode=false

kotlin.incremental=false
kotlin.daemon.jvmargs=-Xms512M -Xmx2G -Dfile.encoding=UTF-8

kotlinVersion=2.2.21
gdxVersion=1.14.0
gdxTeaVMVersion=1.5.3
androidGradlePluginVersion=9.0.0
projectVersion=1.0.0
javaCompatVersion=17
